### PR TITLE
New settings and Advanced example for ListView

### PR DESCRIPTION
**Pull request by gemini1389**
Added new settings `linkPager`, `linkPagerOptions` and `linkPagerWrapperTemplate`.
For events added to the variable {{ias}}. Added an advanced example of using ListView.

### CODE REVIEW

**Comment by thyseus** [comment]
+1 to get this merged !

**Comment by omer-sds** [comment]
its been a hell of long time can we get this merged ,

**Comment by omer-sds** [comment]
is the repo owner even ALIVE!

**Comment by kop** [comment]
@omer-sds yes, repo owner is alive, however, I do not work with Yii2 or PHP anymore and don't have an ability to maintain this repo.

If anyone is interested, I will be happy to add collaborators or put a link in README.md to the maintained fork of this repo.

**Comment by omer-sds** [comment]
good to hear that, may you live long :D , can you please merge this branch atleast . and would be good if you can add @gemini1389  and me as collaborator if you feel ok with it.

**Comment by alfredleo** [comment]
I am willing to colaborate too.

**Pull request merged**
